namespace BannerlordEnvironmentManager.Core.Settings;

// BLSE Standalone reads these three as command-line flags and never from LauncherData.xml. BEM keeps
// them in its own settings for that reason: LauncherEx appends its own elements to LauncherData.xml
// with no de-duplication, so a second writer would accumulate duplicates of all eleven.
//
// Each property is named after what the flag does, not after the LauncherData.xml element LauncherEx
// stores the same setting in. KeepCrashHandlerUnderDebugger in particular is the opposite way round
// from the element DisableCrashHandlerWhenDebuggerIsAttached, and mirroring that name would make true
// mean "off".
public sealed record BlseCrashHandlerOptions(
    bool KeepCrashHandlerUnderDebugger = false,
    bool DisableAutoGeneratedExceptionCatching = false,
    bool UseVanillaCrashHandler = false)
{
    public static BlseCrashHandlerOptions Default { get; } = new();

    public string ToArguments()
    {
        var flags = new List<string>(3);

        if (KeepCrashHandlerUnderDebugger)
            flags.Add("/enablecrashhandlerwhendebuggerisattached");

        if (DisableAutoGeneratedExceptionCatching)
            flags.Add("/disableautogenexceptions");

        if (UseVanillaCrashHandler)
            flags.Add("/enablevanillacrashhandler");

        return string.Join(' ', flags);
    }
}
