using System.Text.Json;
using BannerlordEnvironmentManager.Core.Instances;

namespace BannerlordEnvironmentManager.Core.Launcher;

// What the Play page remembers about one install: which target it launches, the arguments it adds,
// and the crash-handler switches BLSE reads. TargetIndex is only read: it is the pre-dropdown
// positional preference, migrated on load and never written again, since its meaning changes whenever
// a target kind is added.
public sealed record LaunchSettings(
    int? TargetIndex,
    string ExtraArguments,
    bool MinimizeOnLaunch,
    bool? ShowNotes = null,
    string? TargetKind = null,
    bool UseVanillaCrashHandler = false,
    bool DisableAutoGeneratedExceptionCatching = false,
    bool KeepCrashHandlerUnderDebugger = false,
    bool PermitManualLoadOrderOverride = false)
{
    // Module notes start hidden: they are reference material for a load order the player is already
    // reading, not something a freshly downloaded version should open with.
    public const bool ShowNotesDefault = false;

    // What a version that has never been launched through BEM starts from, and the same values the
    // Play page's own properties declare. Switching to such a version has to put these back rather
    // than leave the previous version's arguments and crash-handler switches on screen: the first
    // change afterwards would write them into the new version's file as if they had been chosen for
    // it.
    public static LaunchSettings Defaults { get; } = new(null, string.Empty, false);

    // ShowNotes is nullable so the file can tell "the user turned notes on" apart from "nobody has
    // ever touched this", which is what lets the default change without reaching back into an install
    // the user has already set up. A file that records no value - one written before the setting
    // existed, or by an instance whose notes have never been switched - lands on whatever the default
    // is now. The one case the shape cannot separate is a file written while the old default of on
    // was still in force by some other setting changing, which reads as a deliberate on; keeping the
    // notes the user was already seeing is the safe side of that.
    public bool ShowNotesOrDefault => ShowNotes ?? ShowNotesDefault;
}

// Per version. The target kind, the extra arguments and the three crash-handler switches are all
// command line for one install, and BLSE, which reads those switches, is installed per game folder.
// Machine-wide, an ExtraArguments path aimed at one version went onto another version's command line,
// and PermitManualLoadOrderOverride, which is a safety gate, carried across silently. The resting
// version keeps the exact file it has always read, so nothing migrates.
//
// Read and write throw rather than swallow, unlike the stores whose failure a page has nothing to say
// about: the Play page logs what went wrong and leaves the settings it already had on screen.
public sealed class LaunchSettingsStore(string filePath)
{
    public const string FileName = "launch-settings.json";

    public string FilePath { get; } = filePath;

    public static string GetDefaultPath(InstanceDataRoot? dataRoot = null) =>
        InstanceStateFolder.File(dataRoot, FileName);

    public LaunchSettings Load() =>
        File.Exists(FilePath)
            ? JsonSerializer.Deserialize<LaunchSettings>(File.ReadAllText(FilePath)) ?? LaunchSettings.Defaults
            : LaunchSettings.Defaults;

    public void Save(LaunchSettings settings)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(FilePath)!);
        File.WriteAllText(FilePath, JsonSerializer.Serialize(settings));
    }
}
